(ns alt-frontend.build-hooks.route-registry-generator
  "Shadow-cljs build hook to generate route registry from file structure.

   Conventions:
   - index.cljs in a directory → route is the directory path
   - name.cljs file → route is directory path + /name
   - $param directories/files → becomes :param in route path
   - File path determines route path automatically"
  (:require [clojure.java.io :as io]
            [clojure.string :as str]))

(def routes-dir "src/alt_frontend/routes")
(def registry-file "src/alt_frontend/routes/registry.cljs")

(defn- find-route-files
  "Find all .cljs files in routes directory, excluding registry.cljs"
  []
  (->> (file-seq (io/file routes-dir))
       (filter #(and (.isFile %)
                     (.endsWith (.getName %) ".cljs")
                     (not= (.getName %) "registry.cljs")))
       (sort-by #(.getPath %))))

(defn- file->namespace
  "Convert file path to namespace symbol."
  [file]
  (-> (.getPath file)
      (str/replace #"^src/" "")
      (str/replace #"\.cljs$" "")
      (str/replace "/" ".")
      (str/replace "_" "-")
      symbol))

(defn- segment->route-segment
  "Convert a path segment to route segment.
   $param_name → :param-name
   name_with_underscores → name-with-underscores"
  [segment]
  (if (str/starts-with? segment "$")
    (str ":" (-> segment
                 (subs 1)
                 (str/replace "_" "-")))
    (str/replace segment "_" "-")))

(defn- file->route-path
  "Convert file path to route path.
   routes/agents/$module_id/evaluations.cljs → /agents/:module-id/evaluations
   routes/agents/$module_id/index.cljs → /agents/:module-id"
  [file]
  (let [rel-path (-> (.getPath file)
                     (str/replace #"^src/alt_frontend/routes/" "")
                     (str/replace #"\.cljs$" ""))
        segments (str/split rel-path #"/")
        ;; Remove "index" from the end if present
        segments (if (= "index" (last segments))
                   (butlast segments)
                   segments)
        ;; Convert each segment
        route-segments (map segment->route-segment segments)]
    (if (empty? route-segments)
      "/"
      (str "/" (str/join "/" route-segments)))))

(defn- extract-params
  "Extract parameter names from route path.
   /agents/:module-id/agent/:agent-name → [:module-id :agent-name]"
  [route-path]
  (->> (str/split route-path #"/")
       (filter #(str/starts-with? % ":"))
       (map #(keyword (subs % 1)))
       vec))

(defn- route-path->name
  "Generate route name from route path.
   / → :home
   /agents → :agents
   /agents/:module-id → :module
   /agents/:module-id/evaluations → :evaluations
   /agents/:module-id/agent/:agent-name → :agent
   /agents/:module-id/agent/:agent-name/invocations/:invoke-id → :invocation-detail"
  [route-path]
  (let [segments (->> (str/split route-path #"/")
                      (remove empty?)
                      (remove #(str/starts-with? % ":")))]
    (if (empty? segments)
      :home
      (let [last-seg (last segments)
            ;; Special handling for common patterns
            name (cond
                   ;; If path ends with param, use second-to-last + "-detail"
                   (str/starts-with? (last (str/split route-path #"/")) ":")
                   (str last-seg "-detail")

                   :else last-seg)]
        (keyword name)))))

(defn- namespace->alias
  "Generate a short alias for a namespace."
  [ns-sym]
  (-> (str ns-sym)
      (str/replace "alt-frontend.routes." "routes.")
      symbol))

(defn- build-route-data
  "Build route data from a file."
  [file]
  (let [ns-sym (file->namespace file)
        route-path (file->route-path file)
        params (extract-params route-path)
        route-name (route-path->name route-path)]
    {:namespace ns-sym
     :alias (namespace->alias ns-sym)
     :route-path route-path
     :route-name route-name
     :params params}))

(defn- generate-registry-content
  "Generate the registry.cljs file content."
  [route-data-list]
  (let [namespaces (map :namespace route-data-list)]
    (str ";; AUTO-GENERATED - Do not edit manually\n"
         ";; Generated by alt-frontend.build-hooks.route-registry-generator\n"
         ";; Route paths derived from file structure using $param convention\n\n"
         "(ns alt-frontend.routes.registry\n"
         "  (:require\n"
         (str/join "\n"
                   (for [rd route-data-list]
                     (str "   [" (:namespace rd) " :as " (:alias rd) "]")))
         "))\n\n"
         ";; View components indexed by route name\n"
         "(def views\n"
         "  {" (str/join "\n   "
                         (for [rd route-data-list]
                           (str (:route-name rd) " " (:alias rd) "/view")))
         "})\n\n"
         ";; Auto-generated routes from file structure\n"
         "(def routes\n"
         "  [" (str/join "\n\n   "
                         (for [rd route-data-list]
                           (let [params (:params rd)]
                             (str "[\"" (:route-path rd) "\"\n"
                                  "    {:name " (:route-name rd) "\n"
                                  "     :view " (:alias rd) "/view"
                                  (when (seq params)
                                    (str "\n     :parameters {:path {"
                                         (str/join " " (for [p params] (str p " string?")))
                                         "}}"))
                                  "}]"))))
         "])\n")))

(defn generate-route-registry
  "Build hook to generate routes/registry.cljs before compile.

   Hook signature for shadow-cljs :build-hooks"
  {:shadow.build/stage :configure}
  [build-state & _args]
  (let [files (find-route-files)
        route-data-list (map build-route-data files)
        content (generate-registry-content route-data-list)
        registry (io/file registry-file)]
    ;; Only write if content changed
    (when (or (not (.exists registry))
              (not= (slurp registry) content))
      (spit registry content)
      (println "[alt-frontend] Generated" registry-file "with" (count files) "routes"))
    build-state))
